#!/usr/bin/env python3
"""Tables-pilot task generator — emits clone probes + real-Word ground-truth scripts
from the inline TASKS spec, and merges the task rows into parity/tasks.json.

Per rubric D1.3 (dimension rule): every option that produces DISTINCT file output is
its own task; combinations are not enumerated (one targeted combo: diag x merged).
Probes drive the clone THROUGH ITS UI COMMAND SURFACE (the exact WC.PM/H[cmd] calls the
ribbon controls dispatch). When the UI cannot reach the Word action, the probe records
`unreachable` and exports the base state unchanged — the diff then shows the honest gap.

Run:  python parity/tools/gen_table_probes.py     (from repo root; idempotent)
Generated files carry a GENERATED header — do not hand-edit them.
"""
import json
import os

TOOLS = os.path.dirname(os.path.abspath(__file__))
PARITY = os.path.dirname(TOOLS)
ROOT = os.path.dirname(PARITY).replace("\\", "/")
PROBES = os.path.join(PARITY, "probes")
GT = os.path.join(PARITY, "ground-truth")
TASKS_JSON = os.path.join(PARITY, "tasks.json")

# ---------------------------------------------------------------- templates

PROBE_TEMPLATE = """/* GENERATED by parity/tools/gen_table_probes.py — do not hand-edit.
   Task: {id} — {feature}
   {note} */
(async () => {{
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  for (let i = 0; i < 600 && !window.__WC_READY; i++) await sleep(50);
  const ed = window.WC.editor, PM = window.WC.PM;
  const OUT = '{root}/parity/fixtures/wc-{id}.docx';
  const out = {{ ready: !!window.__WC_READY, id: '{id}', unreachable: null }};
  // -- shared helpers (drive the clone exactly as its UI would) --------------
  const cellPositions = () => {{ const ps = []; ed.state.doc.descendants((n, pos) => {{ if (n.type.name === 'tableCell' || n.type.name === 'tableHeader') ps.push(pos); }}); return ps; }};
  const caretIntoCell = (i) => {{ const ps = cellPositions(); if (i >= ps.length) return false; const $p = ed.state.doc.resolve(ps[i] + 1); const TS = ed.state.selection.constructor; ed.view.dispatch(ed.state.tr.setSelection(TS.near($p))); return true; }};
  const typeInCell = (i, text) => {{ if (!caretIntoCell(i)) return false; ed.commands.insertContent(text); return true; }};
  const applyStyleIfInGallery = (...keys) => {{
    const styles = (PM.getTableStyles && PM.getTableStyles()) || [];
    out.galleryCount = styles.length;
    const hit = styles.find((s) => keys.includes(s.id) || keys.includes(s.name));
    if (!hit) {{ out.unreachable = 'style not in gallery: ' + keys.join(' / '); return false; }}
    PM.tableSetStyle(hit.id); out.appliedStyle = hit.id; return true;
  }};
  const baseTable = async (rows, cols) => {{ out.insertOk = PM.insertTable({{ rows: rows, cols: cols }}); await sleep(300); }};
  // ---------------------------------------------------------------------------
  try {{
    ed.commands.selectAll(); ed.commands.insertContent('<p></p>'); await sleep(60);
{body}
    await sleep(300);
    const bytes = await PM.exportDocxBytes();
    out.save = await window.wordAPI.saveBytes({{ filePath: OUT, bytes }});
  }} catch (e) {{ out.err = String(e && e.message) + '\\n' + String(e && e.stack); }}
  return JSON.stringify(out, null, 2);
}})();
"""

GT_TEMPLATE = """# GENERATED by parity/tools/gen_table_probes.py -- do not hand-edit.
# Task: {id} -- {feature}
# {note}
param([Parameter(Mandatory = $true)][string]$Out)
$ErrorActionPreference = 'Stop'
$pre = @(Get-Process WINWORD -ErrorAction SilentlyContinue | Select-Object -Expand Id)
if ($pre.Count -gt 0) {{ Write-Error "WINWORD already running (PIDs: $($pre -join ',')). Close Word first."; exit 2 }}
$w = New-Object -ComObject Word.Application
$w.Visible = $false
$w.DisplayAlerts = 0
$spawned = @(Get-Process WINWORD -ErrorAction SilentlyContinue | Select-Object -Expand Id | Where-Object {{ $pre -notcontains $_ }})
try {{
    $doc = $w.Documents.Add()
{body}
    if (Test-Path $Out) {{ Remove-Item $Out -Force }}
    $doc.SaveAs2($Out, 16)
    $doc.Close($false)
    Write-Output "saved: $Out"
}} finally {{
    try {{ $w.Quit() }} catch {{}}
    [Runtime.InteropServices.Marshal]::ReleaseComObject($w) | Out-Null
    [GC]::Collect(); [GC]::WaitForPendingFinalizers()
    foreach ($id in $spawned) {{ try {{ Stop-Process -Id $id -Force -ErrorAction SilentlyContinue }} catch {{}} }}
}}
"""

# ---------------------------------------------------------------- GT snippets

RW_BASE = """    $rng = $doc.Range(0, 0)
    $tbl = $doc.Tables.Add($rng, 3, 3, 1, 0)   # wdWord9TableBehavior, wdAutoFitFixed
    $tbl.Style = 'Table Grid'                  # ribbon Insert Table auto-applies it"""

RW_STYLED = RW_BASE + """
    $tbl.Style = 'Grid Table 4 - Accent 1'     # gallery apply (COM == ribbon, worklist B7)"""

def rw_caret(r, c):
    return f"    $w.Selection.SetRange($tbl.Cell({r}, {c}).Range.Start, $tbl.Cell({r}, {c}).Range.Start)"

# ---------------------------------------------------------------- clone snippets

WC_BASE = "    await baseTable(3, 3);"
WC_STYLED = WC_BASE + "\n    applyStyleIfInGallery('GridTable4-Accent1', 'Grid Table 4 Accent 1');\n    await sleep(150);"

def unreachable(reason):
    return f"    out.unreachable = '{reason}';"

# ---------------------------------------------------------------- the spec

T = []  # (id, feature, control_id, note, wc_body, rw_body)

T.append(dict(
    id="tb-insert-dialog", feature="Insert Table dialog: 3x4, fixed width",
    control_id="insert.tables.table.dialog",
    note="Dialog path = same PM.insertTable verb; non-square grid. Word: Tables.Add 3 rows x 4 cols + Table Grid.",
    wc="    out.insertOk = PM.insertTable({ rows: 3, cols: 4 }); await sleep(300);",
    rw="""    $rng = $doc.Range(0, 0)
    $tbl = $doc.Tables.Add($rng, 3, 4, 1, 0)
    $tbl.Style = 'Table Grid'""",
))
T.append(dict(
    id="tb-convert-text-table", feature="Convert Text to Table (commas)",
    control_id="insert.tables.table.converttext",
    note="Clone dialog auto-picks comma when no tabs; PM.textToTable(','). Word: Selection.ConvertToTable(wdSeparateByCommas=2), dialog defaults.",
    wc="""    ed.commands.insertContent('<p>a,b,c</p><p>d,e,f</p>'); await sleep(120);
    ed.commands.selectAll();
    out.converted = PM.textToTable(',');""",
    rw="""    $doc.Range().Text = "a,b,c" + [char]13 + "d,e,f"
    $w.Selection.WholeStory()
    $null = $w.Selection.ConvertToTable(2)""",
))
T.append(dict(
    id="tb-quicktable-calendar", feature="Quick Tables: Calendar",
    control_id="insert.tables.table.quicktables",
    note="Clone Quick Tables 'Calendar' = plain 6x7 grid (fake preset). Word: 'Calendar 1' building block. LoadBuildingBlocks may be needed; if the entry is missing the capture fails honestly.",
    wc="    window.WC.Insert.buildTable(6, 7); await sleep(300); out.note = 'clone Calendar = plain 6x7 grid preset';",
    rw="""    try { $w.Templates.LoadBuildingBlocks() } catch {}
    $entry = $null
    foreach ($t in $w.Templates) { try { $e = $t.BuildingBlockEntries.Item('Calendar 1'); if ($e) { $entry = $e; break } } catch {} }
    if (-not $entry) { throw 'Calendar 1 building block not found in any loaded template' }
    $null = $entry.Insert($doc.Range(0, 0), $true)""",
))
T.append(dict(
    id="tb-style-grid4a1", feature="Table Styles gallery: apply Grid Table 4 Accent 1",
    control_id="table-design.styles.gallery",
    note="The ONE modern style the clone gallery has. Word stamps tblStyle + per-row/cell cnfStyle; expect the cnfStyle gap here.",
    wc=WC_STYLED,
    rw=RW_STYLED,
))
T.append(dict(
    id="tb-style-listtable3", feature="Table Styles gallery: apply List Table 3",
    control_id="table-design.styles.gallery",
    note="NOT in the clone's 2-style gallery -> honest no-op (the 2/247 gap, OOXML leg). Word: Style='List Table 3'.",
    wc=WC_BASE + "\n    applyStyleIfInGallery('ListTable3', 'List Table 3');",
    rw=RW_BASE + "\n    $tbl.Style = 'List Table 3'",
))
# Spec 031: each styleopt task drives the REAL bridge verb PM.tableStyleOption(opt, on) on a styled table
# (the Table Style Options checkbox route) after the GT4A1 apply — the tblLook bit flips + cnfStyle re-stamps.
for sid, prop, val, label, opt, on in [
    ("tb-styleopt-headerrow-off", "ApplyStyleHeadingRows", "$false", "Header Row OFF", "headerRow", "false"),
    ("tb-styleopt-totalrow-on", "ApplyStyleLastRow", "$true", "Total Row ON", "totalRow", "true"),
    ("tb-styleopt-bandedrows-off", "ApplyStyleRowBands", "$false", "Banded Rows OFF", "bandedRows", "false"),
    ("tb-styleopt-firstcol-off", "ApplyStyleFirstColumn", "$false", "First Column OFF", "firstColumn", "false"),
    ("tb-styleopt-lastcol-on", "ApplyStyleLastColumn", "$true", "Last Column ON", "lastColumn", "true"),
    ("tb-styleopt-bandedcols-on", "ApplyStyleColumnBands", "$true", "Banded Columns ON", "bandedColumns", "true"),
]:
    T.append(dict(
        id=sid, feature=f"Table Style Options: {label}",
        control_id="table-design.styleoptions",
        note=f"Word: {prop} = {val} on a styled table (flips a tblLook bit + re-stamps cnfStyle). Clone: PM.tableStyleOption('{opt}', {on}) via the Table Style Options checkbox (spec 031).",
        wc=WC_STYLED + f"\n    out.op = PM.tableStyleOption('{opt}', {on});",
        rw=RW_STYLED + f"\n    $tbl.{prop} = {val}",
    ))
T.append(dict(
    id="tb-shading-cell", feature="Shading: fill caret cell #FFF2CC",
    control_id="table-design.styles.shading",
    note="Clone swatch 1 (#FFF2CC) via tableSetCellShading. Word: BackgroundPatternColor BGR 13431551. Expect the shd val=clear/color=auto attr gap.",
    wc=WC_BASE + "\n    out.shading = PM.tableSetCellShading('#FFF2CC');",
    rw=RW_BASE + "\n    $tbl.Cell(1, 1).Shading.BackgroundPatternColor = 13431551   # RGB(255,242,204) as BGR",
))
# The default pen the Borders dropdown draws with (H.tblBordersApply reads tblPen: 1/2pt auto single).
BORDER_PEN = "{ val: 'single', color: 'auto', size: 4, space: 0 }"
T.append(dict(
    id="tb-borders-all-cell", feature="Borders: All Borders on caret cell",
    control_id="table-design.styles.borders",
    note="Clone 'All Borders' item (032 dropdown) → H.tblBordersApply top/bottom/left/right with the default pen (auto, sz4). Word: caret in cell + ExecuteMso BordersAll. NOTE: on a TableGrid table both write single/auto/4 borders that MATCH the style default — Word absorbs them (no tcBorders); the clone writes them explicit → an 'extra' fidelity note (D1.2 pass-with-note class), not a functional gap.",
    wc=WC_BASE + """
    caretIntoCell(0);
    const P = () => ({ val: 'single', color: 'auto', size: 4, space: 0 });
    out.borders = window.WC.Commands.H.tblBordersApply({ top: P(), bottom: P(), left: P(), right: P() });""",
    rw=RW_BASE + "\n" + rw_caret(1, 1) + "\n    $w.CommandBars.ExecuteMso('BordersAll')",
))
T.append(dict(
    id="tb-borders-none-cell", feature="Borders: No Border on caret cell",
    control_id="table-design.styles.borders",
    note="Clone 'No Border' (032): H.tblBordersApply writes explicit per-side val=nil (all six sides). Word: ExecuteMso BorderNone → per-side w:val=nil.",
    wc=WC_BASE + """
    caretIntoCell(0);
    const NIL = () => ({ val: 'none' });
    out.borders = window.WC.Commands.H.tblBordersApply({ top: NIL(), bottom: NIL(), left: NIL(), right: NIL() });""",
    rw=RW_BASE + "\n" + rw_caret(1, 1) + "\n    $w.CommandBars.ExecuteMso('BorderNone')",
))
T.append(dict(
    id="tb-border-top-cell", feature="Borders: Top Border only (caret cell)",
    control_id="table-design.styles.borders",
    note="Clone 'Top Border' (032 per-edge, merged): H.tblBordersApply({top: pen}). Word: Cell.Borders(wdBorderTop=-1).LineStyle=single.",
    wc=WC_BASE + """
    caretIntoCell(0);
    out.borders = window.WC.Commands.H.tblBordersApply({ top: """ + BORDER_PEN + """ });""",
    rw=RW_BASE + "\n" + rw_caret(1, 1) + "\n    $tbl.Cell(1, 1).Borders(-1).LineStyle = 1",
))
T.append(dict(
    id="tb-border-diagdown-cell", feature="Borders: Diagonal Down (cell 2,2)",
    control_id="table-design.styles.borders",
    note="Clone 'Diagonal Down Border' (032): H.tblBordersApply({tl2br: pen}). Word: Borders(wdBorderDiagonalDown=-7) -> w:tl2br.",
    wc=WC_BASE + """
    caretIntoCell(4);
    out.borders = window.WC.Commands.H.tblBordersApply({ tl2br: """ + BORDER_PEN + """ });""",
    rw=RW_BASE + "\n    $tbl.Cell(2, 2).Borders(-7).LineStyle = 1",
))
T.append(dict(
    id="tb-border-weight-3pt", feature="Border pen weight 3pt (top edge)",
    control_id="table-design.borders.penweight",
    note="Spec 032 T4: the Pen Weight control (H.tblLineWeight) sets tblPen.size; the Borders dropdown then draws with it. The pen-then-draw result is a top border at w:sz=24 (3pt = 24 eighth-points) — the probe drives that end state directly via H.tblBordersApply with an explicit sz=24 pen. Word: LineWidth=wdLineWidth300pt(24) -> w:sz=24.",
    wc=WC_BASE + """
    caretIntoCell(0);
    out.borders = window.WC.Commands.H.tblBordersApply({ top: { val: 'single', color: 'auto', size: 24, space: 0 } });""",
    rw=RW_BASE + """
    $b = $tbl.Cell(1, 1).Borders(-1)
    $b.LineStyle = 1
    $b.LineWidth = 24""",
))
T.append(dict(
    id="tb-border-color-red", feature="Border pen color red (top edge)",
    control_id="table-design.borders.pencolor",
    note="Spec 032 T4: the Pen Color control (H.tblPenColor) sets tblPen.color; the Borders dropdown draws with it. The pen-then-draw result is a top border at w:color=FF0000 — the probe drives that end state directly via H.tblBordersApply with an explicit red pen. Word: Border.Color=RGB red -> w:color=FF0000.",
    wc=WC_BASE + """
    caretIntoCell(0);
    out.borders = window.WC.Commands.H.tblBordersApply({ top: { val: 'single', color: 'FF0000', size: 4, space: 0 } });""",
    rw=RW_BASE + """
    $b = $tbl.Cell(1, 1).Borders(-1)
    $b.LineStyle = 1
    $b.Color = 255   # RGB(255,0,0) as BGR""",
))
for sid, verb, mso, label in [
    ("tb-insert-above", "PM.tableAddRow('above')", "TableRowsInsertAboveWord", "Insert Above"),
    ("tb-insert-below", "PM.tableAddRow('below')", "TableRowsInsertBelowWord", "Insert Below"),
    ("tb-insert-left", "PM.tableAddColumn('left')", "TableColumnsInsertLeft", "Insert Left"),
    ("tb-insert-right", "PM.tableAddColumn('right')", "TableColumnsInsertRight", "Insert Right"),
]:
    T.append(dict(
        id=sid, feature=f"Rows & Columns: {label}",
        control_id="table-layout.rowscols",
        note=f"Clone verb {verb}; Word ExecuteMso {mso} with caret in cell(1,1). Expected genuine-pass candidate (spot-check row).",
        wc=WC_BASE + f"\n    out.op = {verb};",
        rw=RW_BASE + "\n" + rw_caret(1, 1) + f"\n    $w.CommandBars.ExecuteMso('{mso}')",
    ))
T.append(dict(
    id="tb-insert-cells-right", feature="Insert Cells: shift cells right",
    control_id="table-layout.rowscols.launcher",
    note="Clone has no Insert Cells... launcher/dialog (KNOWN GAP #4). Word: Selection.InsertCells(wdInsertCellsShiftRight=0).",
    wc=WC_BASE + "\n" + unreachable("no Insert Cells... launcher or dialog"),
    rw=RW_BASE + """
    $tbl.Cell(1, 1).Range.Select()
    $w.Selection.InsertCells(0)""",
))
T.append(dict(
    id="tb-delete-row", feature="Delete Row (row 1)",
    control_id="table-layout.rowscols.delete",
    note="Clone tableDeleteRow on caret row. Word: Rows(1).Delete.",
    wc=WC_BASE + "\n    out.op = PM.tableDeleteRow();",
    rw=RW_BASE + "\n    $tbl.Rows(1).Delete()",
))
T.append(dict(
    id="tb-delete-col", feature="Delete Column (col 1)",
    control_id="table-layout.rowscols.delete",
    note="Clone tableDeleteColumn on caret col. Word: Columns(1).Delete.",
    wc=WC_BASE + "\n    out.op = PM.tableDeleteColumn();",
    rw=RW_BASE + "\n    $tbl.Columns(1).Delete()",
))
T.append(dict(
    id="tb-delete-table", feature="Delete Table",
    control_id="table-layout.rowscols.delete",
    note="Both sides insert then delete -> near-blank doc. Expected genuine-pass candidate.",
    wc=WC_BASE + "\n    out.op = PM.tableDeleteTable();",
    rw=RW_BASE + "\n    $tbl.Delete()",
))
T.append(dict(
    id="tb-delete-cells-up", feature="Delete Cells: shift cells up (cell 2,2)",
    control_id="table-layout.rowscols.delete",
    note="Clone has no Delete Cells... dialog (flat delete buttons only). Word: Selection.Cells.Delete(wdDeleteCellsShiftUp=1).",
    wc=WC_BASE + "\n" + unreachable("no Delete Cells... dialog (flat Delete Row/Column/Table buttons only)"),
    rw=RW_BASE + """
    $tbl.Cell(2, 2).Range.Select()
    $w.Selection.Cells.Delete(1)""",
))
T.append(dict(
    id="tb-merge-firstrow2", feature="Merge Cells: first two cells of row 1",
    control_id="table-layout.merge",
    note="Clone: tableSelectFirstRowPair + tableMerge -> gridSpan=2. Word: select cells(1,1..2) + Cells.Merge.",
    wc=WC_BASE + """
    PM.tableSelectFirstRowPair();
    out.merge = PM.tableMerge();""",
    rw=RW_BASE + """
    $r = $doc.Range($tbl.Cell(1, 1).Range.Start, $tbl.Cell(1, 2).Range.End)
    $r.Select()
    $w.Selection.Cells.Merge()""",
))
T.append(dict(
    id="tb-split-cell", feature="Split Cells: 1 unmerged cell into 2 columns",
    control_id="table-layout.merge",
    note="Clone tableSplitCell works only on merged cells (no rows/cols dialog) -> expected no-op on a plain cell. Word: Cell(1,1).Split(1,2).",
    wc=WC_BASE + "\n    out.split = PM.tableSplitCell();\n    if (out.split === false) out.unreachable = 'splitCell no-ops on an unmerged cell (no Split Cells dialog)';",
    rw=RW_BASE + "\n    $null = $tbl.Cell(1, 1).Split(1, 2)",
))
T.append(dict(
    id="tb-split-table", feature="Split Table at row 2",
    control_id="table-layout.merge",
    note="Caret in row 2 both sides. Clone tableSplit (splitTableAtRow); Word Selection.SplitTable.",
    wc=WC_BASE + """
    caretIntoCell(3);   // row 2, col 1 in a 3x3
    out.split = PM.tableSplit();""",
    rw=RW_BASE + "\n" + rw_caret(2, 1) + "\n    $w.Selection.SplitTable()",
))
for sid, mode, com, label in [
    ("tb-autofit-contents", "contents", "$tbl.AutoFitBehavior(1)", "AutoFit Contents"),
    ("tb-autofit-window", "window", "$tbl.AutoFitBehavior(2)", "AutoFit Window"),
    ("tb-autofit-fixed", "fixed", "$tbl.AutoFitBehavior(0)", "Fixed Column Width"),
]:
    T.append(dict(
        id=sid, feature=f"AutoFit: {label}",
        control_id="table-layout.cellsize.autofit",
        note=f"Clone tableAutoFit('{mode}'); Word {com}.",
        wc=WC_BASE + f"\n    out.op = PM.tableAutoFit('{mode}');",
        rw=RW_BASE + f"\n    {com}",
    ))
T.append(dict(
    id="tb-dist-rows", feature="Distribute Rows",
    control_id="table-layout.cellsize",
    note="Clone tableDistributeRows; Word select table + Cells.DistributeHeight.",
    wc=WC_BASE + "\n    out.op = PM.tableDistributeRows();",
    rw=RW_BASE + "\n    $tbl.Select()\n    $w.Selection.Cells.DistributeHeight()",
))
T.append(dict(
    id="tb-dist-cols", feature="Distribute Columns",
    control_id="table-layout.cellsize",
    note="Clone tableDistributeColumns; Word select table + Cells.DistributeWidth.",
    wc=WC_BASE + "\n    out.op = PM.tableDistributeColumns();",
    rw=RW_BASE + "\n    $tbl.Select()\n    $w.Selection.Cells.DistributeWidth()",
))
T.append(dict(
    id="tb-rowheight-05in", feature="Row Height 0.5 inch (caret row)",
    control_id="table-layout.cellsize.height",
    note="Clone tableSetRowHeight(48px,'atLeast') (H.tblRowHeight's exact call for 0.5in). Word: Rows(1) HeightRule=atLeast, Height=36pt.",
    wc=WC_BASE + "\n    out.op = PM.tableSetRowHeight(48, 'atLeast');",
    rw=RW_BASE + """
    $tbl.Rows(1).HeightRule = 1
    $tbl.Rows(1).Height = 36""",
))
T.append(dict(
    id="tb-colwidth-15in", feature="Column Width 1.5 inch (caret column)",
    control_id="table-layout.cellsize.width",
    note="Clone tableSetCellWidth(144px) -- note: sets the CELL width; Word Width: sets the whole COLUMN (108pt). Semantic scope difference expected.",
    wc=WC_BASE + "\n    out.op = PM.tableSetCellWidth(144);",
    rw=RW_BASE + "\n    $tbl.Columns(1).Width = 108",
))
T.append(dict(
    id="tb-cellalign-bottomright", feature="Alignment: Align Bottom Right (caret cell)",
    control_id="table-layout.alignment",
    note="Spec 033: Word 9-way = vAlign bottom + paragraph jc right. Clone now has the 9-way grid -> tableSetCellAlign('bottom','right') writes BOTH (w:vAlign bottom + w:jc right). Reachable.",
    wc=WC_BASE + "\n    out.op = PM.tableSetCellAlign('bottom', 'right');",
    rw=RW_BASE + "\n" + rw_caret(1, 1) + """
    $tbl.Cell(1, 1).VerticalAlignment = 3
    $w.Selection.ParagraphFormat.Alignment = 2""",
))
T.append(dict(
    id="tb-textdir", feature="Text Direction: first click (caret cell)",
    control_id="table-layout.alignment.textdir",
    note="Spec 033: Clone H.tblTextDir cycles horizontal->tbRl->btLr; the FIRST click on an un-rotated cell = tbRl (matches Word's first click = rotate 90, wdTextOrientationDownward=3). Later clicks (btLr) are BEHAVIOR territory.",
    wc=WC_BASE + "\n    out.op = PM.tableTextDirectionCycle();",
    rw=RW_BASE + "\n" + rw_caret(1, 1) + "\n    $tbl.Cell(1, 1).Range.Orientation = 3",
))
T.append(dict(
    id="tb-cellmargins", feature="Cell Margins 0.25in all sides",
    control_id="table-layout.alignment.cellmargins",
    note="Spec 033: Word Cell Margins (Table Options) sets TABLE-level default cell margins -> w:tblPr/w:tblCellMar. Clone now writes tableSetTableCellMargins (360 dxa = 0.25in all sides). Matches Word's scope.",
    wc=WC_BASE + "\n    out.op = PM.tableSetTableCellMargins({ top: 360, left: 360, bottom: 360, right: 360 });",
    rw=RW_BASE + """
    $tbl.TopPadding = 18
    $tbl.BottomPadding = 18
    $tbl.LeftPadding = 18
    $tbl.RightPadding = 18""",
))
T.append(dict(
    id="tb-sort-col1", feature="Sort: table rows by column 1 ascending",
    control_id="table-layout.data.sort",
    note="Spec 033 PART B: Clone now has table Sort (WC.Dialogs.tableSort -> WC.PM.tableSort). Fill c/b/a down column 0, sort col 0 asc with hasHeader=true (Word's SortAscending() auto-detects the header row -> pins row 1 'c' and sorts rows 2-3 b/a -> a/b). Result textOrder = c,a,b, matching rw-tb-sort-col1. Doubles as the differ order-sensitivity canary (textOrder).",
    wc=WC_BASE + """
    typeInCell(0, 'c'); typeInCell(3, 'b'); typeInCell(6, 'a');
    caretIntoCell(0);
    out.op = PM.tableSort([{ col: 0, type: 'text', asc: true }], true);""",
    rw=RW_BASE + """
    $tbl.Cell(1, 1).Range.Text = 'c'
    $tbl.Cell(2, 1).Range.Text = 'b'
    $tbl.Cell(3, 1).Range.Text = 'a'
    $tbl.SortAscending()""",
))
T.append(dict(
    id="tb-repeatheader", feature="Repeat Header Rows (row 1)",
    control_id="table-layout.data.repeatheader",
    note="Spec 033: Clone Repeat Header Rows writes the caret row's w:trPr/w:tblHeader (tableRepeatHeaderRows(true)) -- Word's real semantics (Rows(1).HeadingFormat=true), NOT the old <th> conversion.",
    wc=WC_BASE + "\n    out.op = PM.tableRepeatHeaderRows(true);",
    rw=RW_BASE + "\n    $tbl.Rows(1).HeadingFormat = $true",
))
T.append(dict(
    id="tb-totext-tab", feature="Convert to Text (tabs)",
    control_id="table-layout.data.totext",
    note="Clone tableToText('\\t') (H.tblToText's exact call). Word ConvertToText(wdSeparateByTabs=1). Expected genuine-pass candidate.",
    wc=WC_BASE + """
    typeInCell(0, 'a'); typeInCell(1, 'b');
    out.op = PM.tableToText('\\t');""",
    rw=RW_BASE + """
    $tbl.Cell(1, 1).Range.Text = 'a'
    $tbl.Cell(1, 2).Range.Text = 'b'
    $null = $tbl.ConvertToText(1)""",
))
T.append(dict(
    id="tb-totext-comma", feature="Convert to Text (commas)",
    control_id="table-layout.data.totext",
    note="Spec 033 PART B: Clone now has a separator dialog (WC.Dialogs.convertToText) — picking Commas calls WC.PM.tableToText(','), the exact call the dialog's OK makes. Word: ConvertToText(wdSeparateByCommas=2). Reachable now.",
    wc=WC_BASE + """
    typeInCell(0, 'a'); typeInCell(1, 'b');
    out.op = PM.tableToText(',');""",
    rw=RW_BASE + """
    $tbl.Cell(1, 1).Range.Text = 'a'
    $tbl.Cell(1, 2).Range.Text = 'b'
    $null = $tbl.ConvertToText(2)""",
))
T.append(dict(
    id="tb-align-center", feature="Table alignment: center",
    control_id="table-design.align",
    note="Clone tableSetAlignment('center') (w:jc). Word Rows.Alignment=wdAlignRowsCenter(1). Expected genuine-pass candidate. (Word keeps this in Properties, not on Design -- STRUCTURE flags the extra group.)",
    wc=WC_BASE + "\n    out.op = PM.tableSetAlignment('center');",
    rw=RW_BASE + "\n    $tbl.Rows.Alignment = 1",
))
T.append(dict(
    id="tb-indent-05in", feature="Table indent from left: 0.5 inch",
    control_id="table-design.align.indent",
    note="Clone tableSetIndent(48px) (w:tblInd). Word Rows.LeftIndent=36pt.",
    wc=WC_BASE + "\n    out.op = PM.tableSetIndent(48);",
    rw=RW_BASE + "\n    $tbl.Rows.LeftIndent = 36",
))
T.append(dict(
    id="tb-float-around", feature="Floating table: text wrapping Around",
    control_id="table-layout.properties.wrap",
    note="Clone has no floating-table authoring (Group E representative). Word: Rows.WrapAroundText=true -> w:tblpPr.",
    wc=WC_BASE + "\n" + unreachable("no text-wrapping/floating-table control"),
    rw=RW_BASE + "\n    $tbl.Rows.WrapAroundText = $true",
))
T.append(dict(
    id="tb-combo-diag-merged", feature="COMBO: diagonal border on a merged cell",
    control_id="table-design.styles.borders",
    note="The rubric D1.3 example combination. Clone: merge works, diagonal unreachable -> partial gap. Word: merge cells(1,1..2) + Borders(DiagonalDown).",
    wc=WC_BASE + """
    PM.tableSelectFirstRowPair();
    out.merge = PM.tableMerge();
    out.unreachable = 'Borders dropdown has no Diagonal Down Border item';""",
    rw=RW_BASE + """
    $r = $doc.Range($tbl.Cell(1, 1).Range.Start, $tbl.Cell(1, 2).Range.End)
    $r.Select()
    $w.Selection.Cells.Merge()
    $tbl.Cell(1, 1).Borders(-7).LineStyle = 1""",
))

# ---------------------------------------------------------------- generation


def main():
    made = []
    for t in T:
        probe = PROBE_TEMPLATE.format(id=t["id"], feature=t["feature"], note=t["note"],
                                      root=ROOT, body=t["wc"])
        with open(os.path.join(PROBES, f"{t['id']}-pilot-probe.js"), "w", encoding="utf-8", newline="\n") as f:
            f.write(probe)
        gt = GT_TEMPLATE.format(id=t["id"], feature=t["feature"], note=t["note"], body=t["rw"])
        with open(os.path.join(GT, f"realword_{t['id']}.ps1"), "w", encoding="utf-8", newline="\n") as f:
            f.write(gt)
        made.append(t["id"])

    data = json.load(open(TASKS_JSON, encoding="utf-8"))
    tasks = data["tasks"]
    by_id = {x["id"]: i for i, x in enumerate(tasks)}
    for t in T:
        row = {
            "id": t["id"], "control_id": t["control_id"], "feature": t["feature"],
            "action": t["feature"], "tab": "Tables", "usage_tier": "TB",
            "realword_method": "com", "note": t["note"],
        }
        if t["id"] in by_id:
            tasks[by_id[t["id"]]] = row
        else:
            tasks.append(row)
    with open(TASKS_JSON, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"generated {len(made)} probes + ground-truth scripts; tasks.json now has {len(tasks)} tasks")


if __name__ == "__main__":
    main()
