#!/usr/bin/env python3
"""Parity task generator — emit a clone probe + a Word-COM ground-truth + a tasks.json entry from a
compact descriptor, so the deep enumeration (variations + dialog fields) doesn't hand-write dozens of
near-identical probe/COM pairs. IDENTIFY-ONLY: this just creates measurement tasks; it never fixes the clone.

A descriptor is a dict:
  { id, feature, tier, clone_call, com_action, note, [select='word'|'para'] }
- clone_call : the ONE JS statement run on the selected "Revenue" (e.g. "PM.setFontSizePt(10.5)").
- com_action : the PowerShell line(s) acting on $r = the "Revenue" range (e.g. "$r.Font.Size = 10.5").

Usage: python parity/tools/gen_tasks.py   (regenerates the BATCH descriptors below + merges into tasks.json)
"""
import os, json

TOOLS = os.path.dirname(os.path.abspath(__file__))
PARITY = os.path.dirname(TOOLS)
ROOT = os.path.dirname(PARITY)
PROBES = os.path.join(PARITY, "probes")
GT = os.path.join(PARITY, "ground-truth")
TASKS = os.path.join(PARITY, "tasks.json")
FIX = "C:/Users/ogutd/OneDrive/Desktop/new-coding/ms-word-clone/parity/fixtures"

PROBE_TMPL = """/* {feature} variation — clone side (generated by parity/tools/gen_tasks.py). Apply to "Revenue", export. */
(async () => {{
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  for (let i = 0; i < 600 && !window.__WC_READY; i++) await sleep(50);
  const ed = window.WC.editor, PM = window.WC.PM, TS = window.__PM_TextSelection;
  const OUT = '{fix}/wc-{id}.docx';
  const out = {{ ready: !!window.__WC_READY }};
  try {{
    ed.commands.selectAll(); ed.commands.insertContent('<p>Revenue</p>');
    ed.commands.selectAll(); ed.commands.unsetAllMarks(); await sleep(80);
    let f = null;
    ed.state.doc.descendants((n, p) => {{ if (f || !n.isText || !n.text) return; const i = n.text.indexOf('Revenue'); if (i >= 0) f = {{ from: p + i, to: p + i + 7 }}; }});
    ed.view.dispatch(ed.view.state.tr.setSelection(TS.create(ed.state.doc, f.from, f.to)));
    {clone_call}; await sleep(110);
    const bytes = await PM.exportDocxBytes();
    out.save = await window.wordAPI.saveBytes({{ filePath: OUT, bytes }});
  }} catch (e) {{ out.err = String(e && e.message) + '\\n' + String(e && e.stack); }}
  return JSON.stringify(out, null, 2);
}})();
"""

COM_TMPL = """# {feature} variation ground truth via COM (generated). SAFE ONLY WHEN NO OTHER WORD IS OPEN.
param([Parameter(Mandatory=$true)][string]$Out)
$ErrorActionPreference = 'Stop'
$pre = @(Get-Process WINWORD -ErrorAction SilentlyContinue | Select-Object -Expand Id)
if ($pre.Count -gt 0) {{ Write-Error "WINWORD already running (PIDs: $($pre -join ',')). Close Word first."; exit 2 }}
$w = New-Object -ComObject Word.Application
$w.Visible = $false
$w.DisplayAlerts = 0
try {{
    $doc = $w.Documents.Add()
    $doc.Content.Text = 'Revenue'
    $r = $doc.Range(0, 7)            # "Revenue"
    {com_action}
    if (Test-Path $Out) {{ Remove-Item $Out -Force }}
    $doc.SaveAs2($Out, 16)
    $doc.Close($false)
    Write-Output "saved: $Out"
}} finally {{
    $w.Quit()
    [Runtime.InteropServices.Marshal]::ReleaseComObject($w) | Out-Null
    [GC]::Collect(); [GC]::WaitForPendingFinalizers()
}}
"""

# ---------------------------------------------------------------- BATCH 1: variations (menu/combo-reachable)
UL = lambda t: "PM.chain([['setUnderline'], ['setMark', 'underline', {{ underlineType: '{}' }}]])".format(t)
BATCH = [
    # underline styles → distinct <w:u w:val> (Word COM Font.Underline: single1 double3 dotted4 dash7 wavy11 words2)
    dict(id="ul-single", feature="Underline single", clone_call=UL("single"), com_action="$r.Font.Underline = 1",
         note="w:u w:val=single. Same as the main 'underline' task; kept as the variation baseline."),
    dict(id="ul-double", feature="Underline double", clone_call=UL("double"), com_action="$r.Font.Underline = 3",
         note="w:u w:val=double."),
    dict(id="ul-dotted", feature="Underline dotted", clone_call=UL("dotted"), com_action="$r.Font.Underline = 4",
         note="w:u w:val=dotted."),
    dict(id="ul-dashed", feature="Underline dashed", clone_call=UL("dash"), com_action="$r.Font.Underline = 7",
         note="w:u w:val=dash."),
    dict(id="ul-wavy", feature="Underline wavy", clone_call=UL("wave"), com_action="$r.Font.Underline = 11",
         note="w:u w:val=wave."),
    dict(id="ul-words", feature="Underline words-only", clone_call=UL("words"), com_action="$r.Font.Underline = 2",
         note="w:u w:val=words (underline words, not spaces)."),
    # font sizes → distinct <w:sz> (half-points). COM Font.Size in points.
    dict(id="sz-10p5", feature="Font size 10.5", clone_call="PM.setFontSizePt(10.5)", com_action="$r.Font.Size = 10.5",
         note="Fractional size → w:sz w:val=21 (10.5pt x2)."),
    dict(id="sz-8", feature="Font size 8", clone_call="PM.setFontSizePt(8)", com_action="$r.Font.Size = 8",
         note="Small size → w:sz w:val=16."),
    dict(id="sz-72", feature="Font size 72", clone_call="PM.setFontSizePt(72)", com_action="$r.Font.Size = 72",
         note="Large size → w:sz w:val=144."),
    # line spacing (menu, clean wdLineSpacing enums) → distinct <w:spacing w:line>
    dict(id="ls-1p0", feature="Line spacing 1.0", clone_call="PM.cmd('setLineHeight', 1)",
         com_action="$r.ParagraphFormat.LineSpacingRule = 0",
         note="Single → w:spacing w:line=240 w:lineRule=auto. COM wdLineSpaceSingle=0."),
    dict(id="ls-1p5", feature="Line spacing 1.5", clone_call="PM.cmd('setLineHeight', 1.5)",
         com_action="$r.ParagraphFormat.LineSpacingRule = 1",
         note="1.5 lines → w:spacing w:line=360 w:lineRule=auto. COM wdLineSpace1pt5=1."),
]

# Intentionally DEFERRED variations (logged for honest coverage):
DEFERRED = [
    "numbering formats (1./a)/i./A.) — live in numbering.xml (abstractNum numFmt), which is COM!=ribbon-dominated; needs the vsto ribbon ground truth.",
    "line spacing exactly/at-least/2.5/3.0(multiple) — Paragraph-dialog modes (wdLineSpaceExactly/AtLeast/Multiple); enumerate in the Paragraph dialog batch.",
    "indentation left/right/first-line/hanging — Paragraph-dialog fields; enumerate in the Paragraph dialog batch.",
]


def main():
    os.makedirs(PROBES, exist_ok=True)
    os.makedirs(GT, exist_ok=True)
    for d in BATCH:
        with open(os.path.join(PROBES, f"{d['id']}-pilot-probe.js"), "w", encoding="utf-8") as f:
            f.write(PROBE_TMPL.format(feature=d["feature"], fix=FIX, id=d["id"], clone_call=d["clone_call"]))
        with open(os.path.join(GT, f"realword_{d['id']}.ps1"), "w", encoding="utf-8") as f:
            f.write(COM_TMPL.format(feature=d["feature"], com_action=d["com_action"]))

    # merge task entries into tasks.json (before the first T1-pilot 'pagenum'), id-deduped
    data = json.load(open(TASKS, encoding="utf-8"))
    existing = {t["id"] for t in data["tasks"]}
    # tier 'TV' = T0/T1 parameter VARIATIONS (a sub-group so `run.py --tier TV` captures just these).
    new = [dict(id=d["id"], control_id="home.font/paragraph.variation", feature=d["feature"], tab="Home",
               usage_tier="TV", action=f"variation: {d['feature']}", realword_method="com", note=d["note"])
           for d in BATCH if d["id"] not in existing]
    # insert before the first pagenum/table pilot
    idx = next((i for i, t in enumerate(data["tasks"]) if t["id"] in ("pagenum", "table")), len(data["tasks"]))
    data["tasks"][idx:idx] = new
    data["_deferred_variations"] = DEFERRED
    json.dump(data, open(TASKS, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    print(f"generated {len(BATCH)} variation probes + COM scripts; merged {len(new)} new tasks into tasks.json")
    print("deferred (logged):")
    for s in DEFERRED:
        print("  -", s)


if __name__ == "__main__":
    main()
