#!/usr/bin/env python3
"""Parity task generator — emit a clone probe + a Word-COM ground-truth + a tasks.json entry from a
compact descriptor, so the deep enumeration (variations + dialog fields) doesn't hand-write dozens of
near-identical probe/COM pairs. IDENTIFY-ONLY: this just creates measurement tasks; it never fixes the clone.

A descriptor is a dict:
  { id, feature, clone_call, com_action, note }
- clone_call : the ONE (or compound ;-separated) JS statement run on the selected "Revenue"
               (e.g. "PM.setFontSizePt(10.5)" or "PM.cmd('setStrike')").
- com_action : the PowerShell line(s) acting on $r = the "Revenue" range (or $doc/$w) in real Word
               (e.g. "$r.Font.Size = 10.5").

Batches (each = one usage_tier so `run.py --tier <T> --capture` captures just that batch, Word closed):
  TV = T0/T1 parameter VARIATIONS (underline styles, font sizes, line spacing).
  FD = Font dialog fields.            PD = Paragraph dialog fields.       CD = Color (More Colors) fields.
  RD = Find/Replace (doc-delta only). ID = Insert/Layout dialog fields.

The non-OOXML-measurable dialog fields (true clone gaps with NO effect path, numbering.xml-only
COM-artifacts, flow-only search modifiers) are NOT captured — they are recorded in IDENTIFIED_GAPS
below and written to tasks.json `_dialog_identified_gaps` for honest logging + the deep report.

Usage: python parity/tools/gen_tasks.py   (regenerates ALL batch descriptors + merges into tasks.json)
"""
import os, json

TOOLS = os.path.dirname(os.path.abspath(__file__))
PARITY = os.path.dirname(TOOLS)
ROOT = os.path.dirname(PARITY)
PROBES = os.path.join(PARITY, "probes")
GT = os.path.join(PARITY, "ground-truth")
TASKS = os.path.join(PARITY, "tasks.json")
FIX = "C:/Users/ogutd/OneDrive/Desktop/new-coding/ms-word-clone/parity/fixtures"

PROBE_TMPL = """/* {feature} — clone side (generated by parity/tools/gen_tasks.py). Apply to "Revenue", export. */
(async () => {{
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  for (let i = 0; i < 600 && !window.__WC_READY; i++) await sleep(50);
  const ed = window.WC.editor, PM = window.WC.PM, TS = window.__PM_TextSelection;
  const OUT = '{fix}/wc-{id}.docx';
  const out = {{ ready: !!window.__WC_READY }};
  try {{
    ed.commands.selectAll(); ed.commands.insertContent('<p>Revenue</p>');
    ed.commands.selectAll(); ed.commands.unsetAllMarks(); await sleep(80);
    let f = null;
    ed.state.doc.descendants((n, p) => {{ if (f || !n.isText || !n.text) return; const i = n.text.indexOf('Revenue'); if (i >= 0) f = {{ from: p + i, to: p + i + 7 }}; }});
    ed.view.dispatch(ed.view.state.tr.setSelection(TS.create(ed.state.doc, f.from, f.to)));
    {clone_call}; await sleep(130);
    const bytes = await PM.exportDocxBytes();
    out.save = await window.wordAPI.saveBytes({{ filePath: OUT, bytes }});
  }} catch (e) {{ out.err = String(e && e.message) + '\\n' + String(e && e.stack); }}
  return JSON.stringify(out, null, 2);
}})();
"""

COM_TMPL = """# {feature} ground truth via COM (generated). SAFE ONLY WHEN NO OTHER WORD IS OPEN.
param([Parameter(Mandatory=$true)][string]$Out)
$ErrorActionPreference = 'Stop'
$pre = @(Get-Process WINWORD -ErrorAction SilentlyContinue | Select-Object -Expand Id)
if ($pre.Count -gt 0) {{ Write-Error "WINWORD already running (PIDs: $($pre -join ',')). Close Word first."; exit 2 }}
$w = New-Object -ComObject Word.Application
$w.Visible = $false
$w.DisplayAlerts = 0
try {{
    $doc = $w.Documents.Add()
    $doc.Content.Text = 'Revenue'
    $r = $doc.Range(0, 7)            # "Revenue"
    {com_action}
    if (Test-Path $Out) {{ Remove-Item $Out -Force }}
    $doc.SaveAs2($Out, 16)
    $doc.Close($false)
    Write-Output "saved: $Out"
}} finally {{
    $w.Quit()
    [Runtime.InteropServices.Marshal]::ReleaseComObject($w) | Out-Null
    [GC]::Collect(); [GC]::WaitForPendingFinalizers()
}}
"""

# ---------------------------------------------------------------- BATCH 1: variations (menu/combo-reachable)
UL = lambda t: "PM.chain([['setUnderline'], ['setMark', 'underline', {{ underlineType: '{}' }}]])".format(t)
VARIATIONS = [
    dict(id="ul-single", feature="Underline single", clone_call=UL("single"), com_action="$r.Font.Underline = 1",
         note="w:u w:val=single. Same as the main 'underline' task; kept as the variation baseline."),
    dict(id="ul-double", feature="Underline double", clone_call=UL("double"), com_action="$r.Font.Underline = 3",
         note="w:u w:val=double."),
    dict(id="ul-dotted", feature="Underline dotted", clone_call=UL("dotted"), com_action="$r.Font.Underline = 4",
         note="w:u w:val=dotted."),
    dict(id="ul-dashed", feature="Underline dashed", clone_call=UL("dash"), com_action="$r.Font.Underline = 7",
         note="w:u w:val=dash."),
    dict(id="ul-wavy", feature="Underline wavy", clone_call=UL("wave"), com_action="$r.Font.Underline = 11",
         note="w:u w:val=wave."),
    dict(id="ul-words", feature="Underline words-only", clone_call=UL("words"), com_action="$r.Font.Underline = 2",
         note="w:u w:val=words (underline words, not spaces)."),
    dict(id="sz-10p5", feature="Font size 10.5", clone_call="PM.setFontSizePt(10.5)", com_action="$r.Font.Size = 10.5",
         note="Fractional size -> w:sz w:val=21 (10.5pt x2)."),
    dict(id="sz-8", feature="Font size 8", clone_call="PM.setFontSizePt(8)", com_action="$r.Font.Size = 8",
         note="Small size -> w:sz w:val=16."),
    dict(id="sz-72", feature="Font size 72", clone_call="PM.setFontSizePt(72)", com_action="$r.Font.Size = 72",
         note="Large size -> w:sz w:val=144."),
    dict(id="ls-1p0", feature="Line spacing 1.0", clone_call="PM.cmd('setLineHeight', 1)",
         com_action="$r.ParagraphFormat.LineSpacingRule = 0",
         note="Single -> w:spacing w:line=240 w:lineRule=auto. COM wdLineSpaceSingle=0."),
    dict(id="ls-1p5", feature="Line spacing 1.5", clone_call="PM.cmd('setLineHeight', 1.5)",
         com_action="$r.ParagraphFormat.LineSpacingRule = 1",
         note="1.5 lines -> w:spacing w:line=360 w:lineRule=auto. COM wdLineSpace1pt5=1."),
]

# ---------------------------------------------------------------- BATCH 2: FONT dialog fields (tier FD)
# Each field's clone_call mirrors the Font dialog OK chain (dialogs.js:619-645); the OOXML axis applies the
# EFFECT directly. underline-color + ligatures are driveable but ABSENT from the dialog (flow gap, see GAPS).
FONT = [
    dict(id="fd-strike", feature="Font dialog: Strikethrough", clone_call="PM.cmd('setStrike')",
         com_action="$r.Font.StrikeThrough = $true", note="w:strike. Dialog Effects checkbox."),
    dict(id="fd-underline-color", feature="Font dialog: Underline color",
         clone_call="PM.cmd('setUnderline'); PM.cmd('setMark', 'underline', { underlineColor: '#FF0000' })",
         com_action="$r.Font.Underline = 1; $r.Font.UnderlineColor = 255",
         note="w:u w:val=single w:color=FF0000. NOT IN DIALOG (Word has an Underline-color dropdown the clone omits) — driveable via bridge."),
    dict(id="fd-superscript", feature="Font dialog: Superscript",
         clone_call="PM.cmd('setMark', 'textStyle', { vertAlign: 'superscript' })",
         com_action="$r.Font.Superscript = $true", note="w:vertAlign w:val=superscript. Dialog Effects checkbox."),
    dict(id="fd-subscript", feature="Font dialog: Subscript",
         clone_call="PM.cmd('setMark', 'textStyle', { vertAlign: 'subscript' })",
         com_action="$r.Font.Subscript = $true", note="w:vertAlign w:val=subscript. Dialog Effects checkbox."),
    dict(id="fd-allcaps", feature="Font dialog: All caps",
         clone_call="PM.cmd('setMark', 'textStyle', { textTransform: 'uppercase' })",
         com_action="$r.Font.AllCaps = $true", note="w:caps. Dialog Effects checkbox (advFxAttrs)."),
    dict(id="fd-smallcaps", feature="Font dialog: Small caps",
         clone_call="PM.cmd('setMark', 'textStyle', { smallCaps: true })",
         com_action="$r.Font.SmallCaps = $true", note="w:smallCaps. 015 owned AdvancedFontEffects attr."),
    dict(id="fd-spacing", feature="Font dialog (Advanced): Character spacing",
         clone_call="PM.cmd('setMark', 'textStyle', { letterSpacing: '1pt' })",
         com_action="$r.Font.Spacing = 1",
         note="Expanded by 1pt -> w:spacing w:val=20 (twentieths). VERIFY pt->twips export."),
    dict(id="fd-scale", feature="Font dialog (Advanced): Character scale",
         clone_call="PM.cmd('setMark', 'textStyle', { w: 150 })",
         com_action="$r.Font.Scaling = 150", note="150% -> w:w w:val=150 (percent). 015 owned attr."),
    dict(id="fd-position", feature="Font dialog (Advanced): Character position",
         clone_call="PM.cmd('setMark', 'textStyle', { position: '3pt' })",
         com_action="$r.Font.Position = 3",
         note="Raised 3pt -> w:position w:val=6 (half-points). VERIFY pt->half-point export."),
    dict(id="fd-ligatures", feature="Font dialog (Advanced): Ligatures (OpenType)",
         clone_call="PM.cmd('setMark', 'textStyle', { fontVariantLigatures: 'common-ligatures' })",
         com_action="$r.Font.Ligatures = 1",
         note="Standard ligatures -> w14:ligatures w14:val=standard (clone common-ligatures). COM wdLigaturesStandard=1 (NOT 2=Contextual). NOT IN DIALOG (Word's Advanced tab has a Ligatures dropdown the clone omits)."),
]

# ---------------------------------------------------------------- BATCH 3: PARAGRAPH dialog fields (tier PD)
# Indent/spacing/line-spacing match the dialog OK chain (dialogs.js:352-366). The 4 pagination fields are
# driveable via updateAttributes but ABSENT from the current dialog DOM (016 adds them) -> flow gap (see GAPS).
PARAGRAPH = [
    dict(id="fd-indent-left", feature="Paragraph dialog: Indent left",
         clone_call="PM.cmd('updateAttributes', 'paragraph', { 'paragraphProperties.indent.left': 720 })",
         com_action="$r.ParagraphFormat.LeftIndent = $w.InchesToPoints(0.5)", note="0.5in -> w:ind w:left=720."),
    dict(id="fd-indent-right", feature="Paragraph dialog: Indent right",
         clone_call="PM.cmd('updateAttributes', 'paragraph', { 'paragraphProperties.indent.right': 720 })",
         com_action="$r.ParagraphFormat.RightIndent = $w.InchesToPoints(0.5)", note="0.5in -> w:ind w:right=720."),
    dict(id="fd-indent-firstline", feature="Paragraph dialog: First-line indent",
         clone_call="PM.cmd('updateAttributes', 'paragraph', { 'paragraphProperties.indent.firstLine': 720 })",
         com_action="$r.ParagraphFormat.FirstLineIndent = $w.InchesToPoints(0.5)", note="0.5in -> w:ind w:firstLine=720."),
    dict(id="fd-indent-hanging", feature="Paragraph dialog: Hanging indent",
         clone_call="PM.cmd('updateAttributes', 'paragraph', { 'paragraphProperties.indent.hanging': 720 })",
         com_action="$r.ParagraphFormat.FirstLineIndent = $w.InchesToPoints(-0.5)",
         note="0.5in -> w:ind w:hanging=720. COM encodes hanging as NEGATIVE FirstLineIndent + may add a paired w:left."),
    dict(id="fd-spacing-before", feature="Paragraph dialog: Spacing before",
         clone_call="PM.cmd('updateAttributes', 'paragraph', { 'paragraphProperties.spacing.before': 240 })",
         com_action="$r.ParagraphFormat.SpaceBefore = 12", note="12pt -> w:spacing w:before=240. COM may add *Auto flags."),
    dict(id="fd-spacing-after", feature="Paragraph dialog: Spacing after",
         clone_call="PM.cmd('updateAttributes', 'paragraph', { 'paragraphProperties.spacing.after': 160 })",
         com_action="$r.ParagraphFormat.SpaceAfter = 8", note="8pt -> w:spacing w:after=160."),
    dict(id="fd-ls-atleast", feature="Paragraph dialog: Line spacing At least",
         clone_call="PM.cmd('updateAttributes', 'paragraph', { 'paragraphProperties.spacing.line': 240, 'paragraphProperties.spacing.lineRule': 'atLeast' })",
         com_action="$r.ParagraphFormat.LineSpacingRule = 3; $r.ParagraphFormat.LineSpacing = 12",
         note="At least 12pt -> w:spacing w:line=240 w:lineRule=atLeast. Folds a deferred variation."),
    dict(id="fd-ls-exactly", feature="Paragraph dialog: Line spacing Exactly",
         clone_call="PM.cmd('updateAttributes', 'paragraph', { 'paragraphProperties.spacing.line': 240, 'paragraphProperties.spacing.lineRule': 'exact' })",
         com_action="$r.ParagraphFormat.LineSpacingRule = 4; $r.ParagraphFormat.LineSpacing = 12",
         note="Exactly 12pt -> w:spacing w:line=240 w:lineRule=exact (COM wdLineSpaceExactly). Folds a deferred variation."),
    dict(id="fd-ls-multiple", feature="Paragraph dialog: Line spacing Multiple",
         clone_call="PM.cmd('setLineHeight', 1.15)",
         com_action="$r.ParagraphFormat.LineSpacingRule = 5; $r.ParagraphFormat.LineSpacing = 13.8",
         note="Multiple 1.15 -> w:spacing w:line=276 w:lineRule=auto. ARTIFACT: 'Multiple' has no distinct OOXML marker (== auto-multiple)."),
    dict(id="fd-pag-widow", feature="Paragraph dialog: Widow/Orphan control off",
         clone_call="PM.cmd('updateAttributes', 'paragraph', { 'paragraphProperties.widowControl': false })",
         com_action="$r.ParagraphFormat.WidowControl = $false",
         note="w:widowControl w:val=0. NOT IN DIALOG (016 adds the Line-and-Page-Breaks tab) — driveable now."),
    dict(id="fd-pag-keepnext", feature="Paragraph dialog: Keep with next",
         clone_call="PM.cmd('updateAttributes', 'paragraph', { 'paragraphProperties.keepNext': true })",
         com_action="$r.ParagraphFormat.KeepWithNext = $true", note="w:keepNext. NOT IN DIALOG (016)."),
    dict(id="fd-pag-keeplines", feature="Paragraph dialog: Keep lines together",
         clone_call="PM.cmd('updateAttributes', 'paragraph', { 'paragraphProperties.keepLines': true })",
         com_action="$r.ParagraphFormat.KeepTogether = $true",
         note="w:keepLines (COM .KeepTogether == OOXML keepLines). NOT IN DIALOG (016)."),
    dict(id="fd-pag-pagebreak", feature="Paragraph dialog: Page break before",
         clone_call="PM.cmd('updateAttributes', 'paragraph', { 'paragraphProperties.pageBreakBefore': true })",
         com_action="$r.ParagraphFormat.PageBreakBefore = $true", note="w:pageBreakBefore. NOT IN DIALOG (016)."),
]

# ---------------------------------------------------------------- BATCH 4: COLOR (More Colors) fields (tier CD)
COLOR = [
    dict(id="fd-fontcolor-custom", feature="Font color: custom RGB (More Colors)",
         clone_call="PM.cmd('setColor', '#3A7BD5')", com_action="$r.Font.TextColor.RGB = 0xD57B3A",
         note="Custom #3A7BD5 -> w:color w:val=3A7BD5. Normalize hex case before diff."),
    dict(id="fd-fontcolor-theme", feature="Font color: THEME color (Accent 2)",
         clone_call="PM.cmd('setColor', '#E97132')", com_action="$r.Font.TextColor.ObjectThemeColor = 5",
         note="THEME GAP: ObjectThemeColor=5 is wdThemeColorAccent2 (resolved hex E97132 in the Aptos theme). Word writes w:color w:val=E97132 w:themeColor=accent2; the clone is sRGB-only (no w:themeColor). The hex is matched here so the ONLY delta is the missing w:themeColor = the isolated fidelity gap."),
]

# ---------------------------------------------------------------- BATCH 5: FIND/REPLACE doc-delta (tier RD)
# Only Replace/Replace-All mutate the doc; Find + the search modifiers are flow-only (recorded in GAPS).
REPLACE = [
    dict(id="fd-replace-all", feature="Find/Replace: Replace All (Revenue->Income)",
         clone_call="PM.findSession('Revenue', {}); PM.replaceAll('Income')",
         com_action="$f = $r.Find\n    $f.ClearFormatting()\n    $f.Replacement.ClearFormatting()\n    $null = $f.Execute('Revenue', $false, $false, $false, $false, $false, $true, 1, $false, 'Income', 2)",
         note="Text-only delta: <w:t>Revenue</w:t> -> <w:t>Income</w:t>, run rPr preserved. Expect 0/0."),
]

# ---------------------------------------------------------------- BATCH 6: INSERT/LAYOUT dialog fields (tier ID)
INSERT_LAYOUT = [
    dict(id="fd-link", feature="Insert Hyperlink (text + address)",
         clone_call="PM.insertLink({ href: 'https://example.com', text: 'Revenue' })",
         com_action="$null = $r.Hyperlinks.Add($r, 'https://example.com', $null, $null, 'Revenue')",
         note="w:hyperlink r:id + rels Target. COM!=ribbon FIDELITY: clone uses a DIRECT w:u/color; Word applies the Hyperlink CHARACTER STYLE (w:rStyle Hyperlink). rId differs (match by Target)."),
    dict(id="fd-margin-top", feature="Page Setup: Top margin 1.25in",
         clone_call="PM.dePageMargins({ top: 1.25, right: 1, bottom: 1, left: 1 })",
         com_action="$doc.PageSetup.TopMargin = $w.InchesToPoints(1.25)",
         note="1.25in -> w:pgMar w:top=1800 (others default 1in=1440). DIALOG LIMITATION: the Custom Margins dialog is a single uniform field — top not independently settable via the dialog."),
    dict(id="fd-margin-left", feature="Page Setup: Left margin 1.5in",
         clone_call="PM.dePageMargins({ top: 1, right: 1, bottom: 1, left: 1.5 })",
         com_action="$doc.PageSetup.LeftMargin = $w.InchesToPoints(1.5)",
         note="1.5in -> w:pgMar w:left=2160 (others 1440). Same single-uniform-field dialog limitation."),
]

# Each batch: (tier, control_id, tab, descriptors)
BATCHES = [
    ("TV", "home.font/paragraph.variation", "Home", VARIATIONS),
    ("FD", "home.font.dialog", "Home", FONT),
    ("PD", "home.paragraph.dialog", "Home", PARAGRAPH),
    ("CD", "home.font.color-dialog", "Home", COLOR),
    ("RD", "home.editing.find-replace", "Home", REPLACE),
    ("ID", "insert/layout.dialog", "Insert", INSERT_LAYOUT),
]

# ---------------------------------------------------------------- Intentionally NOT captured (logged honestly)
# Code-traced gaps + COM-artifact/numbering.xml-only + flow-only fields. Each: (id, dialog, field, kind, detail).
# kind: GAP (real clone gap), ARTIFACT (COM!=ribbon ground-truth artifact), FLOW (no doc delta), FIDELITY (divergence).
IDENTIFIED_GAPS = [
    # --- Font dialog: fields Word has but the clone cannot author (no effect path) ---
    ("fd-double-strike", "Font", "Double strikethrough", "GAP",
     "Word Font.DoubleStrikeThrough -> w:dstrike. The clone has NO checkbox AND no textStyle attr; the w:dstrike translator round-trips on import only. Cannot author via dialog or bridge."),
    ("fd-hidden", "Font", "Hidden", "GAP",
     "Word Font.Hidden -> w:vanish. No clone checkbox and no WC.PM verb; vanish round-trips on import only."),
    ("fd-kerning", "Font", "Kerning for fonts >= N pt", "GAP",
     "Word Font.Kerning -> w:kern (min-size threshold, half-points). No clone control and no textStyle.kern attr."),
    # --- Bullets/Numbering: numbering.xml-only (COM ApplyListTemplate singleLevel vs clone 9-level + minted numId) ---
    ("fd-bullet-font", "Define New Bullet", "Bullet font", "GAP",
     "Word writes abstractNum/lvl/rPr/rFonts; the clone has NO font picker AND applyListDefinition.js:77-78 STRIPS rFonts -> clone never emits a bullet font. numbering.xml-only."),
    ("fd-bullet-align", "Define New Bullet", "Bullet alignment", "GAP",
     "NARROWED by review: the clone DOES emit w:lvlJc=left (Word's default; bullets.json shows it as an 'extra' only "
     "because the COM singleLevel ground truth omits it). The real gap is only the missing Centered/Right alignment "
     "FIELD (applyListDefinition writes numFmt/lvlText but no non-default lvlJc; defineNewBulletDialog has no align control)."),
    ("fd-num-format", "Define New Number Format", "Number format (decimal/letter/roman)", "ARTIFACT",
     "Defining signal lives ONLY in numbering.xml (abstractNum numFmt/lvlText); document.xml has just w:numPr (numId canonicalized). COM ApplyListTemplate writes a singleLevel template vs the clone's 9-level abstract + a minted numId value -> needs a vsto/numbering.xml ground truth."),
    ("fd-num-style-text", "Define New Number Format", "Number format string (lvlText, e.g. %1) )", "ARTIFACT",
     "lvlText is numbering.xml-only; same single-vs-9-level + numId-value divergence as fd-num-format."),
    ("fd-num-gallery", "Numbering gallery", "Format variations 1./1)/A./a)/i./I.", "ARTIFACT",
     "Routes through the fork's toggleOrderedListStyle (own style->numFmt map), mints a new numId; numbering.xml-only, document.xml signal is only w:numPr + 023 pStyle."),
    ("fd-start-at", "Set Numbering Value", "Start at N", "ARTIFACT",
     "Start value lives in a num-instance lvlOverride/startOverride (numbering.xml); Word COM has no exact 'set value to N' verb (template-oriented). Mid-list restart mints a new numId (only document.xml signal, canonicalized)."),
    ("fd-restart", "Set Numbering Value", "Restart / Start new list", "ARTIFACT",
     "numbering.xml lvlOverride/startOverride=1; clone-pins-startOverride vs Word-fresh-num is a structural numbering.xml divergence."),
    ("fd-continue", "Set Numbering Value", "Continue from previous", "ARTIFACT",
     "numbering.xml: absence of lvlOverride (counter continues); document.xml signal = only the numId reference."),
    # --- Color ---
    ("fd-highlight-custom", "Highlight", "Custom (non-keyword) highlight color", "ARTIFACT",
     "NOT A GAP (review): Word's Text Highlight Color dropdown is ALSO 15-keyword-only (no custom-RGB path), and the "
     "clone restricts its highlighter to the same fixed 15-keyword gallery — so clone == Word. The w:shd downgrade in "
     "highlight-translator.js is IMPORT-ONLY dead code (fires only for a non-keyword hex no ribbon path emits)."),
    # --- Find/Replace: flow-only (no doc delta) + one replace-path gap ---
    ("fd-find", "Find/Replace", "Find / Match case / Whole word / Wildcards / Format", "FLOW",
     "Find + all search modifiers produce ZERO document delta (decorations/navigation only) -> flow-verifier axis, not OOXML. Wildcard grammar + whole-word definition differ COM-vs-clone (count, not identity)."),
    ("fd-special-replace", "Find/Replace", "Special codes in the REPLACE box (^p/^t/^l)", "GAP",
     "Word translates ^p/^t/^l in the replacement (new w:p / w:tab / w:br); the clone passes replInput.value LITERALLY (search.ts) so it inserts the literal text '^p' instead of a paragraph break. Real clone gap on the replace path."),
    # --- Insert/Layout ---
    ("fd-table", "Insert Table", "Rows x Cols", "ARTIFACT",
     "COM Tables.Add auto-creates an AutoFit-to-window TableGrid (+tblLook/default borders); the clone builds equal-width gridCols. Row/col COUNTS match; gridCol widths/tblW/borders diverge. (Covered by the existing 'table' pilot.)"),
    ("fd-margin-uniform", "Page Setup", "Independent T/B/L/R margins via the dialog", "GAP",
     "The clone's Custom Margins dialog exposes ONE uniform 'Margin (inches)' input applied to all four sides; Word's Page Setup sets top/bottom/left/right independently. (The bridge dePageMargins verb + presets do support distinct sides — measured via fd-margin-top/left — but the DIALOG cannot.)"),
]


def write_pair(d):
    with open(os.path.join(PROBES, f"{d['id']}-pilot-probe.js"), "w", encoding="utf-8") as f:
        f.write(PROBE_TMPL.format(feature=d["feature"], fix=FIX, id=d["id"], clone_call=d["clone_call"]))
    with open(os.path.join(GT, f"realword_{d['id']}.ps1"), "w", encoding="utf-8") as f:
        f.write(COM_TMPL.format(feature=d["feature"], com_action=d["com_action"]))


def main():
    os.makedirs(PROBES, exist_ok=True)
    os.makedirs(GT, exist_ok=True)
    total = 0
    new_tasks = []
    data = json.load(open(TASKS, encoding="utf-8"))
    existing = {t["id"] for t in data["tasks"]}
    for tier, control_id, tab, batch in BATCHES:
        for d in batch:
            write_pair(d)
            total += 1
            if d["id"] not in existing:
                new_tasks.append(dict(id=d["id"], control_id=control_id, feature=d["feature"], tab=tab,
                                      usage_tier=tier, action=d["feature"], realword_method="com", note=d["note"]))
    # insert all new tasks before the first pagenum/table pilot, preserving order
    idx = next((i for i, t in enumerate(data["tasks"]) if t["id"] in ("pagenum", "table")), len(data["tasks"]))
    data["tasks"][idx:idx] = new_tasks
    data["_deferred_variations"] = [
        "numbering formats (1./a)/i./A.) -> folded into the Bullets/Numbering batch as numbering.xml-only ARTIFACTS (see _dialog_identified_gaps).",
        "line spacing exactly/at-least/multiple -> ENUMERATED in the Paragraph batch (fd-ls-atleast/exactly/multiple).",
        "indentation left/right/first-line/hanging -> ENUMERATED in the Paragraph batch (fd-indent-*).",
    ]
    data["_dialog_identified_gaps"] = [
        dict(id=g[0], dialog=g[1], field=g[2], kind=g[3], detail=g[4]) for g in IDENTIFIED_GAPS
    ]
    # Adversarial-review verdicts (7 skeptic agents) — the VERIFIED classification of every finding.
    # Full detail + fix hints in parity/results/DEEP_T0_T1_REPORT.md §4.
    data["_dialog_review_summary"] = {
        "verified_real_gaps": ["fd-allcaps", "fd-fontcolor-theme", "fd-link(extra-u)", "fd-double-strike",
                               "fd-hidden", "fd-kerning", "fd-bullet-font", "fd-bullet-align(narrowed)",
                               "fd-special-replace", "fd-margin-uniform"],
        "artifacts_not_gaps": ["fd-spacing-after(default-value)", "fd-link(Hyperlink-style: differ-limitation)",
                               "fd-link(UnresolvedMention: Word-boilerplate)", "fd-num-*(COM singleLevel)",
                               "fd-highlight-custom(clone==Word, 15-keyword-only)"],
        "engine_followup": "styles.xml baseline-subtraction is unsound for PRELOADED-vs-LAZY styles (the clone "
                           "preloads its full styles.xml; Word lazily materializes on use) -> false-missing on "
                           "fd-link's Hyperlink style. body/header/footer/numbering unaffected. Fix: diff styles by "
                           "styleId presence/content, not baseline-subtracted signatures. See report 4c.",
        "report": "parity/results/DEEP_T0_T1_REPORT.md",
    }
    json.dump(data, open(TASKS, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    print(f"generated {total} probe+COM pairs across {len(BATCHES)} batches; merged {len(new_tasks)} new tasks into tasks.json")
    print(f"recorded {len(IDENTIFIED_GAPS)} identified gaps (not captured) in tasks.json._dialog_identified_gaps")
    for tier, cid, tab, batch in BATCHES:
        print(f"  {tier}: {len(batch)} tasks")


if __name__ == "__main__":
    main()
