from pathlib import Path
from PIL import Image
from kernel.models import (AppNode, FeatureFile, UIFile, UIContainer,
                           PriorityFile, ShortcutsFile)


class KBWriter:
    """Writes the CONSOLIDATED knowledge base (design: "On-disk layout").

    Fat, self-contained files are the source of truth:
      - features/<feature>.json  = a FeatureFile (feature + all its sub-features inline)
      - ui.json                  = one UIFile (all containers keyed by id)
      - priority.json            = one PriorityFile
      - shortcuts.json           = one ShortcutsFile
    Every writer re-validates through the schema and refuses malformed input before touching
    disk. graph.json is NOT written here — it is generated by kernel/graph_builder.py from
    these files.
    """

    def __init__(self, kb_root: Path, app: str):
        self.root = Path(kb_root) / app

    def _write_json(self, model, path: Path) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(model.model_dump_json(indent=2), encoding="utf-8")
        return path

    def write_app(self, a) -> Path:
        a = AppNode.model_validate(a)
        return self._write_json(a, self.root / "app.json")

    def write_feature_file(self, ff) -> Path:
        """Write one fat features/<feature>.json (feature + inlined sub-features)."""
        ff = FeatureFile.model_validate(ff)
        name = ff.feature.id.removeprefix("feature:")
        return self._write_json(ff, self.root / "features" / (name + ".json"))

    def write_ui(self, ui) -> Path:
        """Write the single ui.json holding ALL containers keyed by id."""
        ui = UIFile.model_validate(ui)
        return self._write_json(ui, self.root / "ui.json")

    def write_priority(self, p) -> Path:
        p = PriorityFile.model_validate(p)
        return self._write_json(p, self.root / "priority.json")

    def write_shortcuts(self, sc) -> Path:
        sc = ShortcutsFile.model_validate(sc)
        return self._write_json(sc, self.root / "shortcuts.json")

    def save_screenshot(self, img: Image.Image, node_id: str, name: str) -> str:
        sanitized_id = node_id.replace(":", "-")
        rel = f"screenshots/{sanitized_id}/{name}.png"
        out = self.root / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        img.save(out)
        return rel

    # --- convenience for incremental building (agent appends one container / feature at a time) ---

    def load_ui(self) -> UIFile:
        p = self.root / "ui.json"
        if p.exists():
            return UIFile.model_validate_json(p.read_text(encoding="utf-8"))
        return UIFile()

    def upsert_container(self, c) -> Path:
        """Add/replace one container in ui.json without the caller re-reading the whole file."""
        c = UIContainer.model_validate(c)
        ui = self.load_ui()
        ui.containers[c.id] = c
        return self.write_ui(ui)
