# GENERATED by parity/tools/gen_table_probes.py -- do not hand-edit.
# Task: tb-quicktable-calendar -- Quick Tables: Calendar
# Clone Quick Tables 'Calendar' = plain 6x7 grid (fake preset). Word: 'Calendar 1' building block. LoadBuildingBlocks may be needed; if the entry is missing the capture fails honestly.
param([Parameter(Mandatory = $true)][string]$Out)
$ErrorActionPreference = 'Stop'
$pre = @(Get-Process WINWORD -ErrorAction SilentlyContinue | Select-Object -Expand Id)
if ($pre.Count -gt 0) { Write-Error "WINWORD already running (PIDs: $($pre -join ',')). Close Word first."; exit 2 }
$w = New-Object -ComObject Word.Application
$w.Visible = $false
$w.DisplayAlerts = 0
$spawned = @(Get-Process WINWORD -ErrorAction SilentlyContinue | Select-Object -Expand Id | Where-Object { $pre -notcontains $_ })
try {
    $doc = $w.Documents.Add()
    try { $w.Templates.LoadBuildingBlocks() } catch {}
    $entry = $null
    foreach ($t in $w.Templates) { try { $e = $t.BuildingBlockEntries.Item('Calendar 1'); if ($e) { $entry = $e; break } } catch {} }
    if (-not $entry) { throw 'Calendar 1 building block not found in any loaded template' }
    $null = $entry.Insert($doc.Range(0, 0), $true)
    if (Test-Path $Out) { Remove-Item $Out -Force }
    $doc.SaveAs2($Out, 16)
    $doc.Close($false)
    Write-Output "saved: $Out"
} finally {
    try { $w.Quit() } catch {}
    [Runtime.InteropServices.Marshal]::ReleaseComObject($w) | Out-Null
    [GC]::Collect(); [GC]::WaitForPendingFinalizers()
    foreach ($id in $spawned) { try { Stop-Process -Id $id -Force -ErrorAction SilentlyContinue } catch {} }
}
