# GENERATED by parity/tools/gen_table_probes.py -- do not hand-edit.
# Task: tb-border-weight-3pt -- Border pen weight 3pt (top edge)
# Spec 032 T4: the Pen Weight control (H.tblLineWeight) sets tblPen.size; the Borders dropdown then draws with it. The pen-then-draw result is a top border at w:sz=24 (3pt = 24 eighth-points) — the probe drives that end state directly via H.tblBordersApply with an explicit sz=24 pen. Word: LineWidth=wdLineWidth300pt(24) -> w:sz=24.
param([Parameter(Mandatory = $true)][string]$Out)
$ErrorActionPreference = 'Stop'
$pre = @(Get-Process WINWORD -ErrorAction SilentlyContinue | Select-Object -Expand Id)
if ($pre.Count -gt 0) { Write-Error "WINWORD already running (PIDs: $($pre -join ',')). Close Word first."; exit 2 }
$w = New-Object -ComObject Word.Application
$w.Visible = $false
$w.DisplayAlerts = 0
$spawned = @(Get-Process WINWORD -ErrorAction SilentlyContinue | Select-Object -Expand Id | Where-Object { $pre -notcontains $_ })
try {
    $doc = $w.Documents.Add()
    $rng = $doc.Range(0, 0)
    $tbl = $doc.Tables.Add($rng, 3, 3, 1, 0)   # wdWord9TableBehavior, wdAutoFitFixed
    $tbl.Style = 'Table Grid'                  # ribbon Insert Table auto-applies it
    $b = $tbl.Cell(1, 1).Borders(-1)
    $b.LineStyle = 1
    $b.LineWidth = 24
    if (Test-Path $Out) { Remove-Item $Out -Force }
    $doc.SaveAs2($Out, 16)
    $doc.Close($false)
    Write-Output "saved: $Out"
} finally {
    try { $w.Quit() } catch {}
    [Runtime.InteropServices.Marshal]::ReleaseComObject($w) | Out-Null
    [GC]::Collect(); [GC]::WaitForPendingFinalizers()
    foreach ($id in $spawned) { try { Stop-Process -Id $id -Force -ErrorAction SilentlyContinue } catch {} }
}
