# GENERATED by parity/tools/gen_table_probes.py -- do not hand-edit.
# Task: tb-textdir -- Text Direction: first click (caret cell)
# Clone H.tblTextDir hardwires 'tbRl'. Word first click = rotate 90 (wdTextOrientationDownward=3, tbRl expected -- VERIFY, D6.3 flag). Later clicks (btLr) are BEHAVIOR territory.
param([Parameter(Mandatory = $true)][string]$Out)
$ErrorActionPreference = 'Stop'
$pre = @(Get-Process WINWORD -ErrorAction SilentlyContinue | Select-Object -Expand Id)
if ($pre.Count -gt 0) { Write-Error "WINWORD already running (PIDs: $($pre -join ',')). Close Word first."; exit 2 }
$w = New-Object -ComObject Word.Application
$w.Visible = $false
$w.DisplayAlerts = 0
$spawned = @(Get-Process WINWORD -ErrorAction SilentlyContinue | Select-Object -Expand Id | Where-Object { $pre -notcontains $_ })
try {
    $doc = $w.Documents.Add()
    $rng = $doc.Range(0, 0)
    $tbl = $doc.Tables.Add($rng, 3, 3, 1, 0)   # wdWord9TableBehavior, wdAutoFitFixed
    $tbl.Style = 'Table Grid'                  # ribbon Insert Table auto-applies it
    $w.Selection.SetRange($tbl.Cell(1, 1).Range.Start, $tbl.Cell(1, 1).Range.Start)
    $tbl.Cell(1, 1).Range.Orientation = 3
    if (Test-Path $Out) { Remove-Item $Out -Force }
    $doc.SaveAs2($Out, 16)
    $doc.Close($false)
    Write-Output "saved: $Out"
} finally {
    try { $w.Quit() } catch {}
    [Runtime.InteropServices.Marshal]::ReleaseComObject($w) | Out-Null
    [GC]::Collect(); [GC]::WaitForPendingFinalizers()
    foreach ($id in $spawned) { try { Stop-Process -Id $id -Force -ErrorAction SilentlyContinue } catch {} }
}
