"""Generate overview.md — the human-readable render of the KB (v2, consolidated).
Derived entirely from the fat files + priority.json; regenerate any time."""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import common

KB = common.APP_KB


def main():
    app = json.loads((KB / "app.json").read_text(encoding="utf-8"))
    ffiles = [json.loads(p.read_text(encoding="utf-8"))
              for p in sorted((KB / "features").glob("*.json"))]
    ui = json.loads((KB / "ui.json").read_text(encoding="utf-8"))["containers"]
    pri = json.loads((KB / "priority.json").read_text(encoding="utf-8"))
    layer_of = {}
    for lay, ids in pri["layers"].items():
        for nid in ids:
            layer_of[nid] = lay
    sc = json.loads((KB / "shortcuts.json").read_text(encoding="utf-8"))["entries"]

    L = []
    L.append(f"# {app['name']} — Home + Insert universe knowledge base")
    L.append("")
    L.append(f"**Version (pinned):** {app['version']}  |  **Platform:** {app['platform']}")
    L.append("")
    L.append(f"{app['what_is_it']} {app['used_for']}")
    L.append("")
    L.append(f"**Who uses it:** {app['who_uses']}")
    L.append("")
    n_subs = sum(len(ff["subfeatures"]) for ff in ffiles)
    n_stub = sum(1 for c in ui.values() if not c.get("explored", True))
    L.append(f"**Contents:** {len(ffiles)} features · {n_subs} sub-features · "
             f"{len(ui)} UI containers ({n_stub} honest stubs) · "
             f"{len(sc)} shortcut keys · layers: " +
             " ".join(f"{k}={len(v)}" for k, v in sorted(pri['layers'].items())))
    L.append("")
    L.append("## Scope")
    L.append("")
    L.append("The HOME and INSERT ribbon tabs plus every CONTEXTUAL tab their features summon "
             "(Table Design/Layout, Picture/Graphics/Shape Format, Chart Design/Format, "
             "SmartArt Design/Format, Equation, Header & Footer). Other always-present tabs are "
             "recorded as unexplored names only. The deprecated standalone WordArt tab is out of "
             "scope: Insert > WordArt in Word 16 produces a modern text-effect shape whose tab "
             "is Shape Format (covered); the legacy tab is reachable only via old COM paths.")
    L.append("")
    L.append("## Features")
    L.append("")
    ctx_first = sorted(ffiles, key=lambda ff: (bool([
        c for c in (ff["feature"].get("trigger_paths") or [])
        if any("ribbon-home" in p or "ribbon-insert" in p for p in (c.get("path") or []))
    ]) is False, ff["feature"]["id"]))
    for ff in ctx_first:
        f = ff["feature"]
        lay = layer_of.get(f["id"], "P4")
        drv = pri["derived_features"].get(f["id"], {})
        L.append(f"### {f['name']}  `{f['id']}`  — {lay}"
                 + (f" (scope: {drv.get('scope')}, ratio {drv.get('ratio')})" if drv else ""))
        L.append("")
        L.append(f"{f['what_it_does']}")
        L.append("")
        if f.get("boundary"):
            L.append("*Boundary feature — deliberately not driven (cloud/add-in/store).*")
            L.append("")
        for s in ff["subfeatures"]:
            slay = layer_of.get(s["id"], "P4")
            sc_txt = f" · `{s['shortcut']}`" if s.get("shortcut") else ""
            opens = f" · opens `{s['opens']}`" if s.get("opens") else ""
            L.append(f"- **{s['name']}** ({slay}){sc_txt}{opens} — {s['what_it_does']}")
        L.append("")
    L.append("## Contextual surfaces (measured trigger conditions)")
    L.append("")
    for cid, c in sorted(ui.items()):
        if c.get("trigger_condition"):
            L.append(f"- `{cid}` — **{c['label']}**: exists only while "
                     f"{c['trigger_condition']} ({len(c.get('children', []))} controls)")
    L.append("")
    L.append("## Honest stubs (deliberately not entered — below the depth budget)")
    L.append("")
    for cid, c in sorted(ui.items()):
        if not c.get("explored", True):
            L.append(f"- `{cid}` ({c['kind']}) — {c.get('label')}")
    L.append("")
    L.append("## Keyboard surface")
    L.append("")
    for keys, e in sorted(sc.items()):
        for b in e["bindings"]:
            tgt = b.get("triggers") or b.get("opens")
            L.append(f"- `{keys}` — {b['effect'][:100]} → `{tgt}` (when: {b['context']})")
    L.append("")
    L.append("*Generated by scripts/tools/generate_overview.py — never hand-edited.*")
    (KB / "overview.md").write_text("\n".join(L), encoding="utf-8")
    print(f"overview.md written: {len(L)} lines")


if __name__ == "__main__":
    main()
