#!/usr/bin/env python3
"""behavior_verify.py — the BEHAVIOR axis (rubric D6): run the flow cards.

Cards live in parity/behavior/cards/*.json (journey flows D6.1 + micro-twins D6.2). This
engine bundles them into a wrapper evalfile (window.__BEHAVIOR_CARDS), runs the clone probe
(parity/flow/behavior-probe.js), and writes the ledger. Verdicts:
  pass    — every step ok
  pending — contains ❓ from-recording expectations (D6.3: resolved by a real-Word recording,
            NEVER guessed) — reported, does not gate
  fail    — a step failed (the reason names the exact step)

Usage: python parity/engines/behavior_verify.py [--capture] [--report-only]
Outputs parity/results/BEHAVIOR_LEDGER.md + behavior.json.
Exit: 0 / 1 on fails (unless --report-only) / 2 harness failure.
"""
import glob
import json
import os
import subprocess
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
PAR = os.path.join(ROOT, "parity")
CARDS_DIR = os.path.join(PAR, "behavior", "cards")
PROBE = os.path.join(PAR, "flow", "behavior-probe.js")
WRAPPER = os.path.join(PAR, "flow", "_behavior-probe-run.js")
ACTUAL = os.path.join(PAR, "flow", "behavior-actual.json")
RESULTS = os.path.join(PAR, "results")
ELECTRON = os.path.join(ROOT, "node_modules", "electron", "dist", "electron.exe")


def capture(cards):
    with open(WRAPPER, "w", encoding="utf-8") as f:
        f.write("window.__BEHAVIOR_CARDS = " + json.dumps(cards) + ";\n"
                + open(PROBE, encoding="utf-8").read())
    cmd = [ELECTRON, "--user-data-dir=C:/tmp/wc-behavior-profile", "--disable-http-cache", ".",
           f"--probe-out={ACTUAL}", f"--shot-evalfile={WRAPPER}"]
    subprocess.run(cmd, cwd=ROOT, timeout=900, capture_output=True)


def main():
    args = sys.argv[1:]
    cards = []
    for p in sorted(glob.glob(os.path.join(CARDS_DIR, "*.json"))):
        cards.append(json.load(open(p, encoding="utf-8")))
    if not cards:
        print("behavior_verify: no cards in parity/behavior/cards/")
        return 2
    if "--capture" in args or not os.path.exists(ACTUAL):
        capture(cards)
    try:
        actual = json.load(open(ACTUAL, encoding="utf-8"))
    except Exception as e:
        print(f"behavior_verify: harness failure: {e}")
        return 2
    if not actual.get("ready"):
        print("behavior_verify: probe not ready")
        return 2

    rows = actual.get("cards", [])
    counts = {v: sum(1 for r in rows if r.get("verdict") == v) for v in ("pass", "pending", "fail")}
    bymeta = {c["id"]: c for c in cards}
    for r in rows:   # carry card metadata into the output (feature_ledger rolls up by feature)
        r["feature"] = bymeta.get(r["id"], {}).get("feature")

    os.makedirs(RESULTS, exist_ok=True)
    md = ["# Behavior Ledger — flow cards + micro-twins vs the live clone (D6)\n",
          "Auto-generated by `parity/engines/behavior_verify.py`. BEHAVIOR is a SAMPLE and this",
          "ledger says so (D6.4); ❓ from-recording expectations report PENDING until a real-Word",
          "recording resolves them — never guessed (D6.3).\n",
          f"**Cards ({len(rows)}, sampled):** pass {counts['pass']} · pending {counts['pending']} · "
          f"**fail {counts['fail']}**\n",
          "| Card | Kind | Signed-off | Verdict | First failing / pending step |", "|---|---|---|---|---|"]
    for r in rows:
        meta = bymeta.get(r["id"], {})
        first = next((s["result"] for s in r.get("steps", [])
                      if str(s["result"]).startswith(("FAIL", "PENDING"))), "")
        md.append(f"| {r['id']} | {r.get('kind', '?')} | {'yes' if meta.get('signedOff') else 'NO'} | "
                  f"{r['verdict']} | {first} |")
    md.append("\n## Step detail (fails + pendings)\n")
    for r in rows:
        bad = [s for s in r.get("steps", []) if str(s["result"]).startswith(("FAIL", "PENDING"))]
        if bad:
            md.append(f"**{r['id']}**")
            for s in bad:
                md.append(f"- {s['step']} → {s['result']}")
    with open(os.path.join(RESULTS, "BEHAVIOR_LEDGER.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(md) + "\n")
    with open(os.path.join(RESULTS, "behavior.json"), "w", encoding="utf-8") as f:
        json.dump({"counts": counts, "cards": rows}, f, indent=1)

    print(f"BEHAVIOR: pass {counts['pass']} / pending {counts['pending']} / FAIL {counts['fail']} "
          f"(of {len(rows)} sampled cards)")
    print("ledger: parity/results/BEHAVIOR_LEDGER.md")
    if counts["fail"] and "--report-only" not in args:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
