#!/usr/bin/env python3
"""Ledger writer — aggregates per-task diff results into LEDGER.md + ledger.json.

The ledger is the single record of all clone-vs-real-Word differences, and the
input to the develop/fix backlog. missing_nodes = "clone must ADD"; extra_nodes =
"clone over-emits (fidelity)".
"""
import json, os

TIER_ORDER = {"T0": 0, "T1": 1, "T2": 2, "T3": 3, "T4": 4}


def write_ledger(results, out_dir):
    results = sorted(results, key=lambda r: (TIER_ORDER.get(r.get("usage_tier"), 9), r.get("tab", ""), r.get("id", "")))
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "ledger.json"), "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    n = len(results)
    npass = sum(1 for r in results if r.get("verdict") == "semantic-pass")
    md = []
    md.append("# Parity Ledger — clone vs. real Microsoft Word\n")
    md.append("Auto-generated by `parity/engines/run.py`. **missing** = clone must ADD (gap / missing hidden default); "
              "**extra** = clone over-emits (fidelity warning). Verdict `semantic-pass` = clone emits everything Word does "
              "(may still have fidelity warnings).\n")
    md.append(f"**Tasks:** {n} · **semantic-pass:** {npass} · **gap:** {n - npass}\n")
    md.append("## Scoreboard\n")
    md.append("| Task | Feature | Tab | Tier | Verdict | match | missing | extra |")
    md.append("|---|---|---|---|---|--:|--:|--:|")
    for r in results:
        c = r.get("counts", {})
        v = "✅ pass" if r.get("verdict") == "semantic-pass" else "🟠 gap"
        md.append(f"| `{r.get('id')}` | {r.get('feature')} | {r.get('tab')} | {r.get('usage_tier')} | {v} "
                  f"| {c.get('match',0)} | {c.get('missing',0)} | {c.get('extra',0)} |")
    md.append("")
    md.append("## Per-task differences\n")
    for r in results:
        md.append(f"### `{r.get('id')}` — {r.get('feature')} ({r.get('tab')} · {r.get('usage_tier')}) — {r.get('verdict')}\n")
        if r.get("note"):
            md.append(f"_{r.get('note')}_\n")
        miss = r.get("missing_nodes", [])
        extra = r.get("extra_nodes", [])
        pc = r.get("part_counts", {})
        md.append(f"**Clone must ADD ({len(miss)}):**")
        md += [f"- `{m}`" for m in miss] or ["- _(none)_"]
        md.append(f"\n**Clone over-emits / fidelity ({len(extra)}):**")
        md += [f"- `{e}`" for e in extra] or ["- _(none)_"]
        struct = [f"{k}: word={v['word']} clone={v['clone']}" for k, v in pc.items() if v.get("word") != v.get("clone")]
        if struct:
            md.append("\n**Part-count divergence:** " + "; ".join(struct))
        md.append("")
    with open(os.path.join(out_dir, "LEDGER.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    return os.path.join(out_dir, "LEDGER.md")


def write_spec_seeds(results, out_dir):
    """Emit SPEC_SEEDS.md — one spec-ready block per FEATURE, aggregating the gaps
    of all its sub-tasks into functional/fidelity requirements + a parity-backed
    acceptance criterion. Paste a block straight into /speckit-specify."""
    os.makedirs(out_dir, exist_ok=True)
    # group sub-tasks by feature
    feats = {}
    for r in results:
        feats.setdefault(r.get("feature", r.get("id")), []).append(r)
    ordered = sorted(feats.items(), key=lambda kv: (TIER_ORDER.get(kv[1][0].get("usage_tier"), 9), kv[0]))

    md = ["# Spec Seeds — parity gaps → /speckit-specify input\n"]
    md.append("Auto-generated from the parity ledger. Each block is a feature whose clone output diverges "
              "from real Word. Feed a block to `/speckit-specify`; the **ground-truth fixture** is the "
              "definition of correct behavior and the **acceptance** command is the regression gate.\n")
    for feat, group in ordered:
        ids = [g.get("id") for g in group]
        tab = group[0].get("tab"); tier = group[0].get("usage_tier")
        total_missing = sum(len(g.get("missing_nodes", [])) for g in group)
        total_extra = sum(len(g.get("extra_nodes", [])) for g in group)
        allpass = all(g.get("verdict") == "semantic-pass" for g in group)
        md.append(f"## {feat}  ({tab} · {tier})\n")
        md.append(f"**Goal:** make the clone's `{feat}` output match real Microsoft Word.")
        md.append(f"**Sub-tasks covered:** {', '.join('`'+i+'`' for i in ids)}")
        md.append(f"**Ground truth:** " + ", ".join(f"`parity/fixtures/rw-{i}.docx`" for i in ids))
        md.append(f"**Current parity:** {'semantic-pass (fidelity-only)' if allpass else 'GAP'} "
                  f"— {total_missing} missing node(s), {total_extra} fidelity warning(s)\n")

        # functional requirements from missing nodes
        md.append("### Functional requirements — clone MUST emit (from `missing`)")
        frs = []
        for g in group:
            for m in g.get("missing_nodes", []):
                frs.append(f"- FR ({g.get('id')}): emit `{m}`")
        md += frs or ["- _(none — clone already emits everything Word does)_"]

        # fidelity requirements from extra nodes
        md.append("\n### Fidelity requirements — clone over-emits (from `extra`)")
        fids = []
        for g in group:
            for e in g.get("extra_nodes", []):
                fids.append(f"- FID ({g.get('id')}): stop emitting (or justify) `{e}`")
        md += fids or ["- _(none)_"]

        # structural
        structs = []
        for g in group:
            for k, v in g.get("part_counts", {}).items():
                if v.get("word") != v.get("clone"):
                    structs.append(f"- STR ({g.get('id')}): `{k}` parts — Word={v['word']}, clone={v['clone']}")
        if structs:
            md.append("\n### Structural requirements")
            md += structs

        # acceptance
        md.append("\n### Acceptance (regression gate)")
        md.append("```")
        for i in ids:
            md.append(f"python parity/engines/run.py --only {i}   # expect: semantic-pass, missing = 0")
        md.append("```")
        md.append("\n### Next steps")
        md.append(f"`/speckit-specify` (paste this block) → `/speckit-plan` → `/speckit-tasks` → implement → re-run acceptance.\n")
        md.append("---\n")
    with open(os.path.join(out_dir, "SPEC_SEEDS.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    return os.path.join(out_dir, "SPEC_SEEDS.md")
