#!/usr/bin/env python3
"""state_verify.py — the STATE matrix (rubric D2.4): enabled/disabled fidelity.

For every control PAIRED by the structure axis (idMso ↔ clone cmd, from structure.json),
compares real Word's GetEnabledMso answer against the clone's rendered wc-disabled state in
the same canonical contexts:
  ctx1 caret-in-text · ctx2 text-selected · ctx3 caret-in-table

This is CUA/RL observation-space fidelity: a control clickable in the clone but grayed in
real Word teaches an agent wrong behavior (and vice versa).

Usage:
  python parity/engines/state_verify.py                # verify cached captures
  python parity/engines/state_verify.py --capture      # re-run the CLONE probe first
  (the WORD side is captured separately: parity/oracle/capture_enabled_states.ps1 — needs
   Word closed; its TSV is cached in parity/oracle/_enabled_states.tsv)
  --report-only  never exit 1 on mismatches

Outputs parity/results/STATE_LEDGER.md + state.json.
Exit: 0 ok / 1 mismatches (unless --report-only) / 2 harness failure.
"""
import json
import os
import subprocess
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
PAR = os.path.join(ROOT, "parity")
WORD_TSV = os.path.join(PAR, "oracle", "_enabled_states.tsv")
STRUCTURE = os.path.join(PAR, "results", "structure.json")
PROBE = os.path.join(PAR, "flow", "state-probe.js")
ACTUAL = os.path.join(PAR, "flow", "state-actual.json")
RESULTS = os.path.join(PAR, "results")
ELECTRON = os.path.join(ROOT, "node_modules", "electron", "dist", "electron.exe")
CONTEXTS = ["ctx1", "ctx2", "ctx3"]
CTX_LABEL = {"ctx1": "caret in text", "ctx2": "text selected", "ctx3": "caret in table"}


def capture():
    cmd = [ELECTRON, "--user-data-dir=C:/tmp/wc-state-profile", "--disable-http-cache", ".",
           f"--probe-out={ACTUAL}", f"--shot-evalfile={PROBE}"]
    subprocess.run(cmd, cwd=ROOT, timeout=240, capture_output=True)


def load_pairs():
    """(idMso, cmd) pairs from the structure axis — matched + label-differs + type-mismatch."""
    s = json.load(open(STRUCTURE, encoding="utf-8"))
    pairs = []
    seen = set()
    for tab, r in s["per_tab"].items():
        for bucket in ("matched", "label_differs", "type_mismatch"):
            for p in r.get(bucket, []):
                cmd = p["clone"].get("cmd")
                mso = p["word"]["idMso"]
                if cmd and (mso, cmd) not in seen:
                    seen.add((mso, cmd))
                    pairs.append({"idMso": mso, "cmd": cmd, "label": p["word"]["label"], "tab": tab})
    return pairs


def main():
    args = sys.argv[1:]
    if "--capture" in args or not os.path.exists(ACTUAL):
        capture()
    try:
        word = {}
        for line in open(WORD_TSV, encoding="utf-8").read().splitlines():
            parts = line.split("\t")
            if len(parts) == 4:
                word[parts[0]] = [{"True": True, "False": False}.get(v) for v in parts[1:]]
        actual = json.load(open(ACTUAL, encoding="utf-8"))
        pairs = load_pairs()
    except Exception as e:
        print(f"state_verify: harness failure: {e}")
        return 2
    if not actual.get("ready") or not actual.get("contexts"):
        print("state_verify: clone probe not ready / no contexts")
        return 2

    rows, mismatches = [], []
    compared = {c: 0 for c in CONTEXTS}
    for p in pairs:
        wstates = word.get(p["idMso"])
        if not wstates:
            continue
        row = dict(p)
        row["diff"] = {}
        for i, ctx in enumerate(CONTEXTS):
            wv = wstates[i]
            cv = actual["contexts"].get(ctx, {}).get(p["cmd"])
            if wv is None or cv is None:
                continue  # unmeasured on one side (control not rendered in that context, etc.)
            compared[ctx] += 1
            if wv != cv:
                row["diff"][ctx] = {"word": wv, "clone": cv}
        if row["diff"]:
            mismatches.append(row)
        rows.append(row)

    os.makedirs(RESULTS, exist_ok=True)
    md = ["# State Ledger — enabled/disabled fidelity vs real Word (D2.4)\n",
          "Auto-generated by `parity/engines/state_verify.py`. Word side = GetEnabledMso per",
          "canonical context (capture_enabled_states.ps1); clone side = the rendered",
          "`wc-disabled` state in the same contexts (state-probe.js). Pairing via the",
          "structure axis. This is RL observation-space fidelity.\n",
          f"**Pairs compared:** " + " · ".join(f"{CTX_LABEL[c]}: {compared[c]}" for c in CONTEXTS),
          f"\n**Mismatching controls: {len(mismatches)}**\n"]
    if mismatches:
        md.append("| Tab | Control | Word says | Clone shows | Context |")
        md.append("|---|---|---|---|---|")
        for r in mismatches:
            for ctx, d in r["diff"].items():
                md.append(f"| {r['tab']} | `{r['cmd']}` {r['label']} | "
                          f"{'enabled' if d['word'] else 'DISABLED'} | "
                          f"{'enabled' if d['clone'] else 'DISABLED'} | {CTX_LABEL[ctx]} |")
    with open(os.path.join(RESULTS, "STATE_LEDGER.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(md) + "\n")
    with open(os.path.join(RESULTS, "state.json"), "w", encoding="utf-8") as f:
        json.dump({"compared": compared, "mismatches": mismatches}, f, indent=1)

    print(f"STATE: compared {compared} / MISMATCHES {len(mismatches)}")
    print("ledger: parity/results/STATE_LEDGER.md")
    if mismatches and "--report-only" not in args:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
